### ISSUE TITLE
 Make plugin_autoloader less "hacky"

### ISSUE THREAD

**Issue by smutek** [naymspace/generator-naymspace-wp-plugin#1]
Hey, 

Checking out your generator and noticed your comment in  the plugin_autoloader method - 

`$className = $namespace[ count($namespace)-1 ]; // this feels very hacky. any suggestions?`

How about:

`$className = end($namespace);`

 #Cool generator. :)

**Comment by pierrebeitz** [comment]
thanks for the suggestion. seems to be working out quite nice! :+1:
